export const LOAD_SUCCESS_SRC =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+/HgAFhAJ/wlseKgAAAABJRU5ErkJggg==';
export const LOAD_FAILURE_SRC = 'LOAD_SUCCESS_SRC';
