@startuml

package "Form Player" {
  [FormPlayerModule] <-- [FormPlayerComponent]
  [FormPlayerComponent] <-- [FormPlayerConfigApiService]
  [FormPlayerComponent] <-- [FormPlayerStartService]
  [FormPlayerStartService] <-- [FormPlayerService]
  [FormPlayerService] <-- [FormPlayerApiService]
}

[FormPlayerApiService] <..> FormPlayerApi

package "Core" {
  [CoreModule] -> [FormPlayerModule]
  [CoreModule] <-- [CoreComponents...]
  [CoreModule] <-- [CoreServices...]
  [CoreServices...] .. [InitDataService]
  [CoreServices...] .. [ConfigService]
  [ConfigService] --> [FormPlayerApiService]
  [InitDataService] --> [FormPlayerComponent]
  [InitDataService] --> [FormPlayerStartService]
  [InitDataService] --> [FormPlayerApiService]
}




@enduml
