export enum BusEventType {
  ResetFilter = 'resetFilter',
  CloseApp = 'closeApp',
  SuggestionDeleteEvent = 'suggestionDeleteEvent',
  SuggestionsEditEvent = 'suggestionsEditEvent',
  SuggestionSelectedEvent = 'suggestionSelectedEvent',
  PassportValueChangedEvent = 'passportValueChangedEvent',
  CounterValueChanged = 'counterValueChanged',
  FileUploadValueChangedEvent = 'fileUploadValueChangedEvent',
  ValidateOnBlur = 'validateOnBlur',
  UpdateCurrentAnswerServiceStateEvent = 'updateCurrentAnswerServiceStateEvent',
  FileDropped = 'fileDropped',
  ScreenButtonClicked = 'screenButtonClicked',
  CloneButtonClickEvent = 'cloneButtonClickEvent',
  UploaderProcessingStatus = 'uploaderProcessingStatus',
  DeleteCachedValueItem = 'deleteCachedValueItem',
  FileDeletedEvent = 'fileDeletedEvent',
  FileUploadItemValueChangedEvent = 'fileUploadItemValueChangedEvent',
}
