export enum IconType {
  ProgressForm = 'ProgressForm',
  CompleteForm = 'CompleteForm',
  MoveIcon = 'MoveIcon',
  ZoomOut = 'ZoomOut',
  ZoomIn = 'ZoomIn',
  Rotate = 'Rotate',
  Video = 'Video',
  ListFirst = 'ListFirst',
  ListSecond = 'ListSecond',
  PencilLine = 'PencilLine',
  Copy = 'Copy',
  Clip = 'Clip',
  Camera = 'Camera',
  DirectionArrow = 'DirectionArrow',
  Clock = 'Clock',
  Download = 'Download',
  Trash = 'Trash',
  ZoomInMagnifyingGlass = 'ZoomInMagnifyingGlass',
  ZoomOutMagnifyingGlass = 'ZoomOutMagnifyingGlass',
  CurveArrow = 'CurveArrow',
  Plus = 'Plus',
  Menu = 'Menu',
  Map = 'Map',
  Filter = 'Filter',
  Delete = 'Delete',
}
