FROM node:16 as build

WORKDIR /opt
COPY *.json .npmrc ./
COPY /projects/sf-portal/*.json ./projects/sf-portal/
RUN yarn install
COPY . .
RUN yarn build:portal:all

FROM registry.gosuslugi.local/base_images/nginx:1.13.10-1_centos-7.5

COPY --from=build --chown=1000:1000 /opt/dist/sf-portal-st html/sf-portal-st
