export enum UniqueScreenComponentTypes {
  fileUploadComponent = 'FileUploadComponent',
  timeSlot = 'TimeSlot',
  mapService = 'MapService',
  carInfo = 'CarInfo',
  carOwnerInfo = 'CarOwnerInfo',
  carList = 'CarList',
  repeatableFields = 'RepeatableFields',
  employeeHistory = 'EmployeeHistory',
  timer = 'Timer',
  signatureApplication = 'EsepSign',
  paymentScr = 'PaymentScr',
  billInfo = 'BillInfo',
  phoneNumberConfirmCodeInput = 'PhoneNumberConfirmCodeInput',
  ConfirmNewEmail = 'ConfirmNewEmail',
  unusedPayments = 'UnusedPayments',
  photoUploadComponent = 'PhotoUploadComponent',
  paymentTypeSelector = 'PaymentTypeSelector',
  cityDepartment = 'CityDepartment',
  informationCenterPfr = 'InformationCenterPfr',
  fieldList = 'FieldList',
}
