export interface ArgumentsDto {
  vin?: string;
  dictionaryFilterPriority?: DictionaryFilterPriority;
  referralDisclaimerDescription?: string;
  eserviceId?: string;
  sessionId?: string;
  [key: string]: string | unknown; // can be any from linkedValues generated by backend
}

export enum DictionaryFilterPriority {
  secondaryDictionaryFilter = 'secondaryDictionaryFilter',
  dictionaryFilter = 'dictionaryFilter',
}
