export enum ComponentScreenComponentTypes {
  confirmPersonalUserRegAddr = 'ConfirmPersonalUserRegAddr',
  confirmPersonalUserData = 'ConfirmPersonalUserData',
  confirmAnotherUserData = 'ConfirmAnotherUserData',
  confirmChildData = 'ConfirmChildData ',
  confirmPersonalUserEmail = 'ConfirmPersonalUserEmail',
  confirmPersonalUserPhone = 'ConfirmPersonalUserPhone',
  registrationAddr = 'RegistrationAddr',
  passportLookup = 'PassportLookup',
  addPassport = 'AddPassport',
  childrenListUnder14 = 'ChildrenListUnder14',
  childrenListAbove14 = 'ChildrenListAbove14',
  docInput = 'DocInput',
  countryApostil = 'CountryApostil',
  mvdGiac = 'MvdGiac',
  divorceConsent = 'DivorceConsent',
}
