export enum UniqueScreenComponentTypes {
  fileUploadComponent = 'FileUploadComponent',
  addPassport = 'AddPassport',
  timeSlot = 'TimeSlot',
  mapService = 'MapService',
  carInfo = 'CarInfo',
  repeatableFields = 'RepeatableFields',
  employeeHistory = 'EmployeeHistory',
  confirmMarriage = 'ConfirmMarriage',
  genderSelector = 'GenderSelector',
  signatureApplication = 'EsepSign',
  paymentScr = 'PaymentScr',
  phoneNumberConfirmCodeInput = 'PhoneNumberConfirmCodeInput',
  ConfirmNewEmail = 'ConfirmNewEmail',
  unusedPayments = 'UnusedPayments',
  photoUploadComponent = 'PhotoUploadComponent',
}
